### ISSUE TITLE
Unexpected token on spread operator after update to ember-cli 2.14

### ISSUE THREAD

**Issue by acgrama** [stefanpenner/broccoli-persistent-filter#122]
I am working on a bigger app that has been running smoothly for more than a year. Currently we have ember-cli 2.12 as dependency, everything works ok.

As soon as I switch to ember-cli 2.14 from 2.12, I am getting this error:

```
The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: lintTree(app)]: Babel: lintTree(app)] failed with:
SyntaxError: XXX/tests/.../XXX.js: Unexpected token (66:6)
  64 |     const maxDistance = Math.max(...data.map(hole => hole.distance || 0)) || 1;
  65 |     return data.map(hole => ({
> 66 |       ...hole,
     |       ^
  67 |       y: sizes.width / 2 / maxDistance * hole.distance,
  68 |       d: this.shapePath('', sizes.hole),
  69 |     }));
    at Parser.pp$5.raise (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:4452:13)
    at Parser.pp.unexpected (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:4330:10)
    at Parser.pp$3.parsePropertyName (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:4154:96)
    at Parser.pp$3.parseObj (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:4043:12)
    at Parser.pp$3.parseExprAtom (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3717:19)
    at Parser.pp$3.parseExprSubscripts (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3492:19)
    at Parser.pp$3.parseMaybeUnary (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3472:19)
    at Parser.pp$3.parseExprOps (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3402:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3379:19)
    at Parser.pp$3.parseMaybeAssign (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3342:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3826:26)
    at Parser.pp$3.parseExprAtom (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3707:19)
    at Parser.pp$3.parseExprSubscripts (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3492:19)
    at Parser.pp$3.parseMaybeUnary (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3472:19)
    at Parser.pp$3.parseExprOps (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3402:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/src/dev/ui/node_modules/babylon/lib/index.js:3379:19)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (/usr/local/src/dev/ui/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/usr/local/src/dev/ui/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/usr/local/src/dev/ui/node_modules/ember-cli/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at processModulesOnly (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/babel-process-modules-only.js:28:10)
    at EmberApp.lintTestTrees (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1195:17)
    at EmberApp.appTests (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1162:28)
    at EmberApp.test (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1148:28)
    at EmberApp.toArray (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1679:63)
    at EmberApp.toTree (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1694:38)
    at module.exports (/usr/local/src/dev/ui/ember-cli-build.js:26:14)
    at Builder.setupBroccoliBuilder (/usr/local/src/dev/ui/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/usr/local/src/dev/ui/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/usr/local/src/dev/ui/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/usr/local/src/dev/ui/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:554:13)
```

Any ideas what could be the problem? Thanks!

(I have babel-plugin-transform-object-rest-spread and babel-plugin-transform-es2015-destructuring installed as dependencies)

**Comment by rwjblue** [comment]
The README of [ember-cli-babel](https://github.com/babel/ember-cli-babel) specifically describes how to add the rest/spread support with ember-cli-babel@6.  Please take a look over there, and let me know if that doesn't resolve the issue.

I'm going to close this issue (we can open a more specific one in ember-cli-babel repo if needed).

**Comment by acgrama** [comment]
I've added the transform-object-rest-spread plugin as suggested by the readme:
```
  const app = new EmberApp(defaults, {
    babel: {
      plugins: ['transform-object-rest-spread'],
    },
  });
```

Now I am getting this error:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appTestTrees)] failed with:
TypeError: The plugin "transform-object-rest-spread" didn't export a Plugin instance
    at PluginManager.validate (/usr/local/src/dev/ui/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/usr/local/src/dev/ui/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/usr/local/src/dev/ui/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/usr/local/src/dev/ui/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/usr/local/src/dev/ui/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at /usr/local/src/dev/ui/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Object.transformString (/usr/local/src/dev/ui/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (/usr/local/src/dev/ui/node_modules/broccoli-babel-transpiler/index.js:110:22)
    at Babel.processString (/usr/local/src/dev/ui/node_modules/broccoli-babel-transpiler/index.js:210:15)
    at Promise.then.result.output (/usr/local/src/dev/ui/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:1039:33)
    at /usr/local/src/dev/ui/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
    at tryCatch (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/usr/local/src/dev/ui/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/usr/local/src/dev/ui/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/usr/local/src/dev/ui/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:18)
    at EmberApp.appTests (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1154:18)
    at EmberApp.test (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1133:26)
    at EmberApp.toArray (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1680:61)
    at EmberApp.toTree (/usr/local/src/dev/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1695:30)
    at module.exports (/usr/local/src/dev/ui/ember-cli-build.js:29:14)
    at Builder.setupBroccoliBuilder (/usr/local/src/dev/ui/node_modules/ember-cli/lib/models/builder.js:54:19)
    at new Builder (/usr/local/src/dev/ui/node_modules/ember-cli/lib/models/builder.js:33:10)
    at ServeTask.run (/usr/local/src/dev/ui/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at Win.checkIfSymlinksNeedToBeEnabled.then (/usr/local/src/dev/ui/node_modules/ember-cli/lib/commands/serve.js:78:29)
    at tryCatch (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:538:13)
    at /usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/usr/local/src/dev/ui/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Not sure if I'm doing it right, but didn't solve my issue. Do you need any other information from me, like installed versions, etc.?

**Comment by telmaantunes** [comment]
solution?

**Comment by yashhy** [comment]
@telmaantunes Thanks a lot.  Was facing this issue for one whole day 🗡
