### ISSUE TITLE
broccoli-persistent-filter - childprocess fail

### ISSUE THREAD

**Issue by theoldcounty** [stefanpenner/broccoli-persistent-filter#160]
Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: ember-lodash]` plugin. 💥
Worker terminated unexpectedly
Error: Worker terminated unexpectedly
    at ChildProcess.<anonymous> (/opt/home/jenkins/workspace/_CORE-2815_wrong-question-for-US/site/src/ember/node_modules/workerpool/lib/WorkerHandler.js:181:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
:site:emberTest FAILED

**Comment by stefanpenner** [comment]
broccoli-persistent-filter doesn’t provide workers. This error seems strange and likely incomplete.

Can you please include version of node, and the plugin causing issues. Ideally also a reproduction, as is this isn’t actionable yet.

**Comment by theoldcounty** [comment]
still getting the error.
I believe the node version is v6.14.3 or v6.11.0 (this is what I think failed on Jenkins)

microplugin#0.0.3 bower_components/microplugin
:site:emberBuild Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: ember-lodash]` plugin. 💥
Worker terminated unexpectedly
Error: Worker terminated unexpectedly
    at ChildProcess.<anonymous> (/opt/home/jenkins/workspace/uestions-preview-tooltips-part-2/site/src/ember/node_modules/workerpool/lib/WorkerHandler.js:181:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 FAILED

**Comment by stefanpenner** [comment]
Can you share the version of ember-lodash?

**Comment by theoldcounty** [comment]
this has failed again after the update - again - please stop

```

pikaday#1.4.0 bower_components/pikaday
:site:emberBuild Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: ember-lodash]` plugin. 💥
Worker terminated unexpectedly
Error: Worker terminated unexpectedly
    at ChildProcess.<anonymous> (/opt/home/jenkins/workspace/ture_CORE-2884-agenda-URL-copier/site/src/ember/node_modules/ember-cli-tooltipster/node_modules/workerpool/lib/WorkerHandler.js:246:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by stefanpenner** [comment]
@theoldcountry as a workaround can you set the environment variable JOBS=1? That should disable the use of workers as we debug this issue.

**Comment by theoldcounty** [comment]
I don't have access to devops. This is breaking builds globally.

```
Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: ember-lodash]` plugin. 💥
Worker terminated unexpectedly
Error: Worker terminated unexpectedly
    at ChildProcess.<anonymous> (/opt/home/jenkins/workspace/-2903-user-name-to-be-filterable/site/src/ember/node_modules/ember-cli-tooltipster/node_modules/workerpool/lib/WorkerHandler.js:246:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
:site:emberTest FAILED

FAILURE: Build failed with an exception.
```

**Comment by stefanpenner** [comment]
> - again - please stop

@theoldcounty  it is not our intention to break anything. As our CI is passing, the issue seems to be pretty unexpected. Although this is understandably annoying, have some patience I will debug shortly.

**Comment by stefanpenner** [comment]
@theoldcounty as asked above could you:

* Can you share the version of ember-lodash?
* Can you share the version of workerpool?

**Comment by stefanpenner** [comment]
Could you also include the version of ember-cli-tooltipster ?

**Comment by stefanpenner** [comment]
Interestingly, while debugging this I am able to reproduce a similar error when:

* running more then 1 workerpool
* starting with a debugger

The error in question, is actually due to the child processes both being told to bind to the same inspector port.

I doubt your jenkins runs are starting processes with a debugger enabled... so the above may not be your issue. But I'll see if we can at-least surface a better error message in this situations.

**Comment by stefanpenner** [comment]
I think we can get the exitStatus code at-least printed. That way, we can surface why the process exited unexpectedly.


In my case, I am getting `exit(12)` which is coming from: https://github.com/nodejs/node/blob/2e2670a2073c89d700ab274a47bb0e6036046e65/src/node.cc#L574

**Comment by stefanpenner** [comment]
I've opened a PR on workerpool, to surface additional information when process's exit unexpectedly: https://github.com/josdejong/workerpool/pull/58

**Comment by stefanpenner** [comment]
I'm still not quite sure what is causing your issue, as I doubt you are enabling the debug port in CI (but maybe you are?)

Anyways, in the meantime I have submitted a fix to workerpool for  the issue \w a debugger and multiple pools which results in Worker Exited Unexpectedly error: https://github.com/josdejong/workerpool/pull/60
