### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by SaladFork** [stefanpenner/broccoli-persistent-filter#38]
Following the recent updates, rebuilds now seem to be broken in my ember-cli app after a `nom`:

Output after changing a file (full path abbreviated to `…` for anonymity):
```
file changed helpers/in-array.js
ENOENT: no such file or directory, unlink …/Dashboard/tmp/output_path-WDavmjzf.tmp/helpers/in-array.js'
Error: ENOENT: no such file or directory, unlink '…/Dashboard/tmp/output_path-WDavmjzf.tmp/helpers/in-array.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:937:18)
    at null.<anonymous> (…/Dashboard/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/broccoli-persistent-filter/index.js:85:12)
    at …/Dashboard/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/broccoli-persistent-filter/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (…/Dashboard/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (…/Dashboard/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:505:17)
    at …/Dashboard/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (…/Dashboard/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

Mac OS X 10.11.1 with Ember CLI 1.13.8.

**Comment by stefanpenner** [comment]
Strange, its strange to see: "file changed helpers/in-array.js" but then no corresponding file to remove.

I am inclined to believe there is something funky going on with jscs/suave

**Comment by stefanpenner** [comment]
found it, the recent persistent-filter changes fail to take target-extension into account.

**Comment by SaladFork** [comment]
:smiley: :+1:

**Comment by stefanpenner** [comment]
➜  broccoli-persistent-filter git:(master) npm publish
+ broccoli-persistent-filter@1.1.3

**Comment by stefanpenner** [comment]
running to a meeting, will write a test and re-release when im back.

**Comment by toranb** [comment]
Thanks for the quick work on this!

**Comment by toranb** [comment]
@stefanpenner I did find this issue is still present w/ 1.1.3 when using both ember s and ember t -s together

**Comment by stefanpenner** [comment]
> @stefanpenner I did find this issue is still present w/ 1.1.3 when using both ember s and ember t -s together

might be a different issue then.

**Comment by stefanpenner** [comment]
@toranb can you share a repro/detailed steps ?

**Comment by toranb** [comment]
@stefanpenner I'll need to try this on a much smaller project (i'll report back tonight if I can repro this w/out my production app)

**Comment by stefanpenner** [comment]
@toranb im trying to replicate on our apps, but am unable to. Maybe im missing some key thing. Anwyays, feel free to open a new issue

**Comment by DimaMklk** [comment]
Hello. Not sure that my issue is the same, but it is very similar. After I save any file `ember server` as well as `ember build -w` is crashing. Project is on going and it's a little bit old

Ubuntu 16.10

node@0.12.18
npm@2.15.11

ember@1.9.1
ember-cli@0.1.12

```
ENOENT, no such file or directory '* path */frontend/tmp/broccoli_persistent_filterbabel-output_path-frHRHzTG.tmp/app/.gitkeep'
Error: ENOENT, no such file or directory '* path */frontend/tmp/broccoli_persistent_filterbabel-output_path-frHRHzTG.tmp/app/.gitkeep'
  at Error (native)
  at Object.fs.statSync (fs.js:797:18)
  at checkIsDirectory (* path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:144:17)
  at mergeRelativePath (* path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:75:29)
  at mergeRelativePath (* path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:122:17)
  at * path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
  at $$$internal$$tryCatch (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
  at $$rsvp$asap$$flush (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at process._tickCallback (node.js:355:11)
```
`npm ls --depth=0`
```
├── broccoli-asset-rev@2.5.0
├── broccoli-ember-hbs-template-compiler@1.7.0
├── ember-cli@0.1.12
├── ember-cli-6to5@3.0.0
├── ember-cli-app-version@0.3.1
├── ember-cli-coffeescript@0.8.0
├── ember-cli-content-security-policy@0.3.0
├── ember-cli-dependency-checker@0.0.7
├── ember-cli-htmlbars@0.6.0
├── ember-cli-ic-ajax@0.1.1
├── ember-cli-inject-live-reload@1.4.1
├── ember-cli-qunit@0.3.1
├── ember-data@1.0.0-beta.12
├── ember-export-application-global@1.1.1
├── express@4.14.0
└── glob@4.5.3
```
`bower ls`
```
├─┬ c3#0.4.11
│ └── d3#3.5.0
├── d3#3.5.0
├─┬ ember#1.9.1
│ ├── handlebars#2.0.0
│ └── jquery#1.12.4
├─┬ ember-cli-shims#0.0.3
│ └── ember#1.9.1
├── ember-cli-test-loader#0.0.4
├─┬ ember-data#1.0.0-beta.14.1
│ └── ember#1.9.1
├─┬ ember-load-initializers#0.0.2
│ └── ember#1.9.1
├─┬ ember-qunit#0.1.8
│ ├── ember#1.9.1
│ └── ember-data#1.0.0-beta.14.1
├─┬ ember-qunit-notifications#0.0.4
│ └── qunit-notifications#0.0.6
├─┬ ember-resolver#0.1.21
│ └── ember#1.9.1
├── handlebars#2.0.0
├── jquery#1.12.4
├── loader.js#1.0.1
├── qunit#1.15.0
└── raygun4js#2.4.3
```

**Comment by hjdivad** [comment]
@DimaMklk

What's the output of `npm ls fs-tree-diff`?

> Project is on going and it's a little bit old
> 
> node@0.12.18
> npm@2.15.11
> 
> ember@1.9.1
> ember-cli@0.1.12

Yup that's a bit old.

**Comment by DimaMklk** [comment]
@hjdivad 
here is output of `npm ls fs-tree-diff` :
```
└─┬ ember-export-application-global@1.1.1
  └─┬ ember-cli-babel@5.2.1
    ├─┬ broccoli-babel-transpiler@5.6.2
    │ ├─┬ broccoli-merge-trees@1.2.1
    │ │ └── fs-tree-diff@0.5.6 
    │ └─┬ broccoli-persistent-filter@1.2.13
    │   └── fs-tree-diff@0.5.6 
    └─┬ broccoli-funnel@1.1.0
      └── fs-tree-diff@0.5.6
```

**Comment by hjdivad** [comment]
@DimaMklk those versions look good to me.

Are you able to reproduce this problem easily in a new repo?

Alternatively is this project publicly accessible and easy to reproduce the error in?

**Comment by DimaMklk** [comment]
@hjdivad, thanks for the reply.
I solved the problem by locking module `ember-export-application-global` to version `1.0.0`.

I deleted the message, so I leave here the error, in case someone else will need some help with it.
```
ENOENT, no such file or directory '* path */frontend/tmp/broccoli_persistent_filterbabel-output_path-frHRHzTG.tmp/app/.gitkeep'
Error: ENOENT, no such file or directory '* path */frontend/tmp/broccoli_persistent_filterbabel-output_path-frHRHzTG.tmp/app/.gitkeep'
  at Error (native)
  at Object.fs.statSync (fs.js:797:18)
  at checkIsDirectory (* path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:144:17)
  at mergeRelativePath (* path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:75:29)
  at mergeRelativePath (* path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:122:17)
  at * path */frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
  at $$$internal$$tryCatch (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
  at $$rsvp$asap$$flush (* path */frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at process._tickCallback (node.js:355:11)
```
