### ISSUE TITLE
test errors w/ hash-for-dep

### ISSUE THREAD

**Issue by shaunc** [stefanpenner/broccoli-persistent-filter#45]
[Without using new hash-for-dep], I get the following errors on test (below).

They can be repaired by replacing 

    F.prototype.baseDir = function() {
      return '../';

With 

    var path = require('path');

    F.prototype.baseDir = function() {
      return path.join(__dirname, '../');

I'll submit a patch in a second... however I have no idea what changed/is different about my env (macosx 10.11.3 node 0.12.4 ... npm 3.6.0)  to cause the failures.

```
  1) Filter persistent cache initializes cache:
     Cannot find module '/Volumes/Macintosh_HD/Users/shauncutts/src/broccoli-persistent-filter/node_modules//package.json'
  Error: Cannot find module 'node_modules//package.json'
      at pkg (node_modules/hash-for-dep/lib/pkg.js:19:20)
      at statPathsFor (node_modules/hash-for-dep/lib/stat-paths-for.js:14:20)
      at hashForDep (node_modules/hash-for-dep/index.js:15:21)
      at Filter.cacheKey (index.js:117:10)
      at Object.module.exports.cacheKey (lib/strategies/persistent.js:22:16)
      at Object.module.exports.init (lib/strategies/persistent.js:12:50)
      at Processor.init (lib/processor.js:16:18)
      at Filter (index.js:56:18)
      at new F (test/test.js:541:14)
      at Context.<anonymous> (test/test.js:564:15)

  2) Filter persistent cache initializes cache using ENV variable if present:
     Cannot find module '/Volumes/Macintosh_HD/Users/shauncutts/src/broccoli-persistent-filter/node_modules//package.json'
  Error: Cannot find module 'node_modules//package.json'
      at pkg (node_modules/hash-for-dep/lib/pkg.js:19:20)
      at statPathsFor (node_modules/hash-for-dep/lib/stat-paths-for.js:14:20)
      at hashForDep (node_modules/hash-for-dep/index.js:15:21)
      at Filter.cacheKey (index.js:117:10)
      at Object.module.exports.cacheKey (lib/strategies/persistent.js:22:16)
      at Object.module.exports.init (lib/strategies/persistent.js:12:50)
      at Processor.init (lib/processor.js:16:18)
      at Filter (index.js:56:18)
      at new F (test/test.js:541:14)
      at Context.<anonymous> (test/test.js:576:15)

  3) Filter persistent cache `cacheKeyProcessString` return correct first level file cache:
     Cannot find module '/Volumes/Macintosh_HD/Users/shauncutts/src/broccoli-persistent-filter/node_modules//package.json'
  Error: Cannot find module 'node_modules//package.json'
      at pkg (node_modules/hash-for-dep/lib/pkg.js:19:20)
      at statPathsFor (node_modules/hash-for-dep/lib/stat-paths-for.js:14:20)
      at hashForDep (node_modules/hash-for-dep/index.js:15:21)
      at Filter.cacheKey (index.js:117:10)
      at Object.module.exports.cacheKey (lib/strategies/persistent.js:22:16)
      at Object.module.exports.init (lib/strategies/persistent.js:12:50)
      at Processor.init (lib/processor.js:16:18)
      at Filter (index.js:56:18)
      at new F (test/test.js:541:14)
      at Context.<anonymous> (test/test.js:600:15)

  4) Filter persistent cache properly reads the file tree:
     Cannot find module '/Volumes/Macintosh_HD/Users/shauncutts/src/broccoli-persistent-filter/node_modules//package.json'
  Error: Cannot find module 'node_modules//package.json'
      at pkg (node_modules/hash-for-dep/lib/pkg.js:19:20)
      at statPathsFor (node_modules/hash-for-dep/lib/stat-paths-for.js:14:20)
      at hashForDep (node_modules/hash-for-dep/index.js:15:21)
      at ReplaceFilter.Filter.cacheKey (index.js:117:10)
      at Object.module.exports.cacheKey (lib/strategies/persistent.js:22:16)
      at Object.module.exports.init (lib/strategies/persistent.js:12:50)
      at Processor.init (lib/processor.js:16:18)
      at ReplaceFilter.Filter (index.js:56:18)
      at new ReplaceFilter (test/helpers/replacer.js:15:10)
      at ReplaceFilter (test/helpers/replacer.js:12:12)
      at node_modules/broccoli-test-helpers/index.js:63:29
      at lib$rsvp$$internal$$initializePromise (node_modules/rsvp/dist/rsvp.js:541:9)
      at new lib$rsvp$promise$$Promise (node_modules/rsvp/dist/rsvp.js:757:9)
      at node_modules/broccoli-test-helpers/index.js:62:12
      at Context.<anonymous> (test/test.js:611:14)
```

**Comment by stefanpenner** [comment]
thanks for fixing
